# Файл конфигурации "инфраструктура как код" для Render.
# Он создает ТОЛЬКО бесплатную базу данных.

# Раздел для баз данных
databases:
  - name: coin-sifter-db
    databaseName: coinsifterdb
    user: coinsifter_user
    plan: free # База данных остается на бесплатном плане
    region: frankfurt

