name: Run Coin Sifter

on:
  # Позволяет запускать рабочий процесс вручную с вкладки Actions на GitHub
  workflow_dispatch:

  schedule:
    # Запускает скрипт в 00:00 UTC первого числа каждого месяца.
    # Вы можете изменить это расписание. Примеры:
    # - cron: '0 * * * *'    # Запускать каждый час
    # - cron: '0 */4 * * *'   # Запускать каждые 4 часа
    # - cron: '0 0 * * *'     # Запускать каждый день в полночь UTC
    - cron: '0 0 1 * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Этот шаг загружает ваш код (main.py, requirements.txt и т.д.)
      uses: actions/checkout@v4

    - name: Set up Python
      # Этот шаг настраивает нужную версию Python и включает кэширование
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # Ключевая строка для кэширования

    - name: Install dependencies
      # Устанавливает все библиотеки из вашего файла requirements.txt
      # Благодаря кэшу, этот шаг будет почти мгновенным со второго запуска
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the main script
      # Запускает ваш основной скрипт
      env:
        # Безопасно передает адрес вашей базы данных из секретов GitHub
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python main.py

