name: Run Coin Sifter

on:
  workflow_dispatch: # Позволяет запускать вручную
  schedule:
    - cron: '0 2 1 * *' # Первого числа каждого месяца в 2 часа ночи UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the main script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py

